### ISSUE TITLE
Custom audios and metadata

### ISSUE THREAD

**Issue by Tywors** [ttaoREtw/Tacotron-pytorch#5]
Hello!
I'm trying training my spanish voice, but i have problems with especials characters (for example: ñ) 

But i try my own wavs files and metadata without any special character but i have the same problem, when i strart training (main.py) i have this error:

[INFO] Load data
[INFO] Build model
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    solver.build_model()
  File "/content/Tacotron-pytorch/src/solver.py", line 80, in build_model
    self.model = Tacotron(**self.config['model']['tacotron']).to(device=self.device)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 386, in to
    return self._apply(convert)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/rnn.py", line 127, in _apply
    self.flatten_parameters()
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/rnn.py", line 123, in flatten_parameters
    self.batch_first, bool(self.bidirectional))
**RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED**

I'm using default config:
tacotron:
        n_vocab: 250 # Use a larger vocab size is ok.
        embedding_size: 256
        mel_size: 80
        linear_size: 1025
        r: 5

The self.device it's correct because with LJSpeech work fine.
Have you any idea about this error?

Thanks man! 
PD: excellents result with LJSpeech

**Comment by ttaoREtw** [comment]
It seems that it is not about data because the error comes from `solver.build_model()`.
Have you seen [this](https://discuss.pytorch.org/t/runtimeerror-cudnn-error-cudnn-status-execution-failed/31169/8) and [this](https://github.com/OpenNMT/OpenNMT-py/issues/1163) issues? 
I think you should check the versions of your **pytorch** and **cuda**.

**Comment by Tywors** [comment]
Hello,
sorry friend i think that is one issue from google colab, sometimes it works sometimes no...
Can open a issue if i need help in the future with spanish especials characters or one email is better?

thanks!

**Comment by ttaoREtw** [comment]
No problem.
